### ISSUE TITLE
No matching distribution found for stair_dxf

### ISSUE THREAD

**Issue by lanhao945** [iblofcqu/iblofcqu.github.io#8]
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://iblofcqu.github.io
ERROR: Could not find a version that satisfies the requirement stair_dxf (from versions: none)
ERROR: No matching distribution found for stair_dxf
```

同时,访问 https://iblofcqu.github.io/stair-dxf/ 时,显示404 

![image](https://user-images.githubusercontent.com/34086198/231027080-8ad67d93-3c08-4593-ad3d-3a861b35a4b9.png)

**Comment by xuchengran** [comment]
因为网络原因，还没打上tags

**Comment by zc19950602** [comment]
> ```
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://iblofcqu.github.io
> ERROR: Could not find a version that satisfies the requirement stair_dxf (from versions: none)
> ERROR: No matching distribution found for stair_dxf
> ```
> 
> 同时,访问 https://iblofcqu.github.io/stair-dxf/ 时,显示404
> 
> ![image](https://user-images.githubusercontent.com/34086198/231027080-8ad67d93-3c08-4593-ad3d-3a861b35a4b9.png)
你现在试试

**Comment by lanhao945** [comment]
仍然无法安装,相同表现
